# 1. Información del Taller
site_name: Tutoriales de FreeCAD 0.19
site_description: Mis notas de esta versión del programa de diseño 3D
site_author: Federico Coca
site_url: https://fgcoca.github.io/Tutoriales-FreeCAD-0.19

# 2. Repositorio
repo_name: fgcoca/Tutoriales-FreeCAD-0.19
repo_url: https://github.com/fgcoca/Tutoriales-FreeCAD-0.19
edit_uri: ""

# 3. Copyright
copyright: Copyright &copy; 2020 - 2021 Federico Coca

# 4. RRSS
# extra:
#  social:
#    - type: 'github'
#      link: 'https://github.com/fgcoca'
#    - type: 'twitter'
#      link: 'https://twitter.com/fgcoca'

# 5. Navegación # TODO:
nav:
  - Introducción: index.md 
  - Tutoriales: 
    - 1-Body en PartDesign: Tutoriales/01-Body.md
    - 2-Creacion de las vistas de una pieza: Tutoriales/02-Vistas.md
    - 3-Plano referencia que pasa por tres puntos: Tutoriales/03-PR-3-puntos.md
  #  - 4-Plano referencia fijado a objetos: Tutoriales/04-PR-fijado-obj.md
  #  - 5-Repaso extrusión por barrido y referencia normal: Tutoriales/05-PR-normal.md
  - Archivos 3D: 
    - Formatos de archivos: Ejercicios/formatos.md
    - Ejercicios y fichas: Ejercicios/ejercicios-export.md
 #     - Fuentes: Ejercicios/src.md
 #     - Exportados: Ejercicios/export.md
  - Miscelanea:
    - Autor: Miscelanea/about.md 
    - Licencias: Miscelanea/lic.md
    - Webgrafia/Bibliografía: Miscelanea/webgrafia.md
    - Software utilizado: Miscelanea/soft.md

# 6. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 7. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    primary: light blue
    accent: deep purple 
  font:
    text: Roboto 
    code: Roboto Mono
  logo: img/favicon.png 
  favicon: img/favicon.png 
  language: es
  extra:
      search:
        language: es, en
  # Página 404
  static_templates:
    - 404.html
  # No incluir los JavaScript de MkDocs
  #include_search_page: false
  #search_index_only: true

# 8. Extensiones
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      # guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 9. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  # Este fichero es opcional y solo si se quiere sobreescribir la configuracion del plugin
  #- js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# 10. Plugins
plugins:
  - search
  - minify:
      minify_html: true
